### ISSUE TITLE
While trying to access dashboard it is giving 404 error

### ISSUE THREAD

**Issue by rahul123-dotcom** [mkobaly/jiraworklog#1] opened 2021-01-30 09:39 UTC
As per document http://localhost:8180/issues.html is the dashboard url but it is giving 404 error while accessing.

**Comment by mkobaly** [comment] 2021-02-19 20:56
Could you add a bit more details as to how you are trying to run the application? 

- linux or windows? 
- released version or are you compiling the code yourself? 
- Backend is MS SQL Server or BoldDB?

I made some big fixes recently. I typically used SQL server as my backend and BoltDB was not complete. It should be working now with BoltDB.

**Comment by rahul123-dotcom** [comment] 2021-03-10 10:30
I am running the .exe file on windows, I have tried the new release also. But I am getting 404. May be the web files are missing I guess. And also in newer version(V0.2.0) getting the below error for resolution updater job.
`time="2021-03-10 15:55:05" level=error msg="job run failed" app=jiraWorklog error="unknown error getting issue details from jira. id=: Not 200 response 405" job=JiraResolutionUpdater`

**Comment by mkobaly** [comment] 2021-03-23 20:59
Did you edit your configuration file and enter in your Jira connection info correctly? You should ensure you can talk to Jira first via their API. Maybe try using Postman to test. The error is stating you are not getting a successful message back from Jira

**Comment by mkobaly** [comment] 2021-12-13 14:29
Closing since unable to reproduce

**Closed as completed by mkobaly** 2021-12-13 14:29 UTC
